-- FILE 7: supabase.sql

-- =========================================================
-- GLAMSANITY SUPABASE DATABASE
-- =========================================================

create extension if not exists pgcrypto;

-- =========================================================
-- PRODUCTS
-- =========================================================

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text default '',
  category text default '',
  price numeric(12,2) default 0,
  stock integer default 0,
  stock_checked_date date,
  image_url text default '',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.products
  add column if not exists description text default '';

alter table public.products
  add column if not exists category text default '';

alter table public.products
  add column if not exists price numeric(12,2) default 0;

alter table public.products
  add column if not exists stock integer default 0;

alter table public.products
  add column if not exists stock_checked_date date;

alter table public.products
  add column if not exists image_url text default '';

alter table public.products
  add column if not exists created_at timestamptz default now();

alter table public.products
  add column if not exists updated_at timestamptz default now();


-- =========================================================
-- BUNDLES
-- =========================================================

create table if not exists public.bundles (
  id bigint generated by default as identity primary key,
  name text not null,
  description text default '',
  price numeric(12,2) default 0,
  stock integer default 0,
  stock_checked_date date,
  image_url text default '',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.bundles
  add column if not exists description text default '';

alter table public.bundles
  add column if not exists price numeric(12,2) default 0;

alter table public.bundles
  add column if not exists stock integer default 0;

alter table public.bundles
  add column if not exists stock_checked_date date;

alter table public.bundles
  add column if not exists image_url text default '';

alter table public.bundles
  add column if not exists created_at timestamptz default now();

alter table public.bundles
  add column if not exists updated_at timestamptz default now();


-- =========================================================
-- PRE-ORDER CONTAINERS
-- =========================================================

create table if not exists public.containers (
  id bigint generated by default as identity primary key,
  name text not null,
  description text default '',
  price numeric(12,2) default 0,
  stock integer default 0,
  stock_checked_date date,
  lead_time text default '',
  image_url text default '',
  source text default '',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.containers
  add column if not exists description text default '';

alter table public.containers
  add column if not exists price numeric(12,2) default 0;

alter table public.containers
  add column if not exists stock integer default 0;

alter table public.containers
  add column if not exists stock_checked_date date;

alter table public.containers
  add column if not exists lead_time text default '';

alter table public.containers
  add column if not exists image_url text default '';

alter table public.containers
  add column if not exists source text default '';

alter table public.containers
  add column if not exists created_at timestamptz default now();

alter table public.containers
  add column if not exists updated_at timestamptz default now();


-- =========================================================
-- SERVICES
-- =========================================================

create table if not exists public.services (
  id bigint generated by default as identity primary key,
  name text not null,
  description text default '',
  image_url text default '',
  sort_order integer default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.services
  add column if not exists description text default '';

alter table public.services
  add column if not exists image_url text default '';

alter table public.services
  add column if not exists sort_order integer default 0;

alter table public.services
  add column if not exists created_at timestamptz default now();

alter table public.services
  add column if not exists updated_at timestamptz default now();


-- =========================================================
-- GLAMSANITY SETTINGS
-- =========================================================

create table if not exists public.glamsanity_settings (
  id bigint primary key,
  company_introduction text default '',
  mission text default '',
  vision text default '',
  services_offered jsonb default '[]'::jsonb,
  payment_information jsonb default '{}'::jsonb,
  rules_policy_images jsonb default '[]'::jsonb,
  payment_mode_images jsonb default '[]'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.glamsanity_settings
  add column if not exists company_introduction text default '';

alter table public.glamsanity_settings
  add column if not exists mission text default '';

alter table public.glamsanity_settings
  add column if not exists vision text default '';

alter table public.glamsanity_settings
  add column if not exists services_offered jsonb default '[]'::jsonb;

alter table public.glamsanity_settings
  add column if not exists payment_information jsonb default '{}'::jsonb;

alter table public.glamsanity_settings
  add column if not exists rules_policy_images jsonb default '[]'::jsonb;

alter table public.glamsanity_settings
  add column if not exists payment_mode_images jsonb default '[]'::jsonb;

alter table public.glamsanity_settings
  add column if not exists created_at timestamptz default now();

alter table public.glamsanity_settings
  add column if not exists updated_at timestamptz default now();


insert into public.glamsanity_settings (id)
values (1)
on conflict (id) do nothing;


-- =========================================================
-- ENABLE RLS
-- =========================================================

alter table public.products enable row level security;
alter table public.bundles enable row level security;
alter table public.containers enable row level security;
alter table public.services enable row level security;
alter table public.glamsanity_settings enable row level security;


-- =========================================================
-- REMOVE OLD POLICIES
-- =========================================================

drop policy if exists "Public read products" on public.products;
drop policy if exists "Public insert products" on public.products;
drop policy if exists "Public update products" on public.products;
drop policy if exists "Public delete products" on public.products;

drop policy if exists "Public read bundles" on public.bundles;
drop policy if exists "Public insert bundles" on public.bundles;
drop policy if exists "Public update bundles" on public.bundles;
drop policy if exists "Public delete bundles" on public.bundles;

drop policy if exists "Public read containers" on public.containers;
drop policy if exists "Public insert containers" on public.containers;
drop policy if exists "Public update containers" on public.containers;
drop policy if exists "Public delete containers" on public.containers;

drop policy if exists "Public read services" on public.services;
drop policy if exists "Public insert services" on public.services;
drop policy if exists "Public update services" on public.services;
drop policy if exists "Public delete services" on public.services;

drop policy if exists "Public read settings" on public.glamsanity_settings;
drop policy if exists "Public insert settings" on public.glamsanity_settings;
drop policy if exists "Public update settings" on public.glamsanity_settings;
drop policy if exists "Public delete settings" on public.glamsanity_settings;


-- =========================================================
-- PRODUCTS POLICIES
-- =========================================================

create policy "Public read products"
on public.products
for select
to anon, authenticated
using (true);

create policy "Public insert products"
on public.products
for insert
to anon, authenticated
with check (true);

create policy "Public update products"
on public.products
for update
to anon, authenticated
using (true)
with check (true);

create policy "Public delete products"
on public.products
for delete
to anon, authenticated
using (true);


-- =========================================================
-- BUNDLES POLICIES
-- =========================================================

create policy "Public read bundles"
on public.bundles
for select
to anon, authenticated
using (true);

create policy "Public insert bundles"
on public.bundles
for insert
to anon, authenticated
with check (true);

create policy "Public update bundles"
on public.bundles
for update
to anon, authenticated
using (true)
with check (true);

create policy "Public delete bundles"
on public.bundles
for delete
to anon, authenticated
using (true);


-- =========================================================
-- CONTAINER POLICIES
-- =========================================================

create policy "Public read containers"
on public.containers
for select
to anon, authenticated
using (true);

create policy "Public insert containers"
on public.containers
for insert
to anon, authenticated
with check (true);

create policy "Public update containers"
on public.containers
for update
to anon, authenticated
using (true)
with check (true);

create policy "Public delete containers"
on public.containers
for delete
to anon, authenticated
using (true);


-- =========================================================
-- SERVICES POLICIES
-- =========================================================

create policy "Public read services"
on public.services
for select
to anon, authenticated
using (true);

create policy "Public insert services"
on public.services
for insert
to anon, authenticated
with check (true);

create policy "Public update services"
on public.services
for update
to anon, authenticated
using (true)
with check (true);

create policy "Public delete services"
on public.services
for delete
to anon, authenticated
using (true);


-- =========================================================
-- SETTINGS POLICIES
-- =========================================================

create policy "Public read settings"
on public.glamsanity_settings
for select
to anon, authenticated
using (true);

create policy "Public insert settings"
on public.glamsanity_settings
for insert
to anon, authenticated
with check (true);

create policy "Public update settings"
on public.glamsanity_settings
for update
to anon, authenticated
using (true)
with check (true);

create policy "Public delete settings"
on public.glamsanity_settings
for delete
to anon, authenticated
using (true);


-- =========================================================
-- STORAGE BUCKET
-- =========================================================

insert into storage.buckets (id, name, public)
values (
  'glamsanity-images',
  'glamsanity-images',
  true
)
on conflict (id)
do update set public = true;


-- =========================================================
-- STORAGE POLICIES
-- =========================================================

drop policy if exists "Public can view Glamsanity images"
on storage.objects;

drop policy if exists "Public can upload Glamsanity images"
on storage.objects;

drop policy if exists "Public can update Glamsanity images"
on storage.objects;

drop policy if exists "Public can delete Glamsanity images"
on storage.objects;


create policy "Public can view Glamsanity images"
on storage.objects
for select
to anon, authenticated
using (
  bucket_id = 'glamsanity-images'
);


create policy "Public can upload Glamsanity images"
on storage.objects
for insert
to anon, authenticated
with check (
  bucket_id = 'glamsanity-images'
);


create policy "Public can update Glamsanity images"
on storage.objects
for update
to anon, authenticated
using (
  bucket_id = 'glamsanity-images'
)
with check (
  bucket_id = 'glamsanity-images'
);


create policy "Public can delete Glamsanity images"
on storage.objects
for delete
to anon, authenticated
using (
  bucket_id = 'glamsanity-images'
);


-- =========================================================
-- OPTIONAL DEFAULT PAYMENT STRUCTURE
-- =========================================================

update public.glamsanity_settings
set payment_information = coalesce(
  payment_information,
  '{}'::jsonb
)
where id = 1;


-- =========================================================
-- IMPORTANT NEW FIELDS
--
-- Products:
--   stock
--   stock_checked_date
--
-- Bundles:
--   stock
--   stock_checked_date
--
-- Containers:
--   stock
--   stock_checked_date
--   lead_time
--   source
--
-- Settings:
--   payment_information
--   rules_policy_images
--   payment_mode_images
--
-- All are included above.
-- =========================================================