-- ============================================
-- GLAMSANITY DATABASE
-- ============================================

create table if not exists products (
    id bigint generated by default as identity primary key,
    name text not null,
    category text not null,
    description text default '',
    ingredients text default '',
    benefits text default '',
    size text default '',
    packaging text default '',
    moq text default '',
    price text default '',
    image text default '',
    created_at timestamptz default now()
);

create table if not exists containers (
    id bigint generated by default as identity primary key,
    name text not null,
    size text default '',
    color text default '',
    qty text default '',
    availability text default 'onhand',
    created_at timestamptz default now()
);

create table if not exists bundles (
    id bigint generated by default as identity primary key,
    name text not null,
    price text default '',
    details text default '',
    image text default '',
    created_at timestamptz default now()
);

create table if not exists glamsanity_settings (
    id integer primary key,
    company_intro text default '',
    updated_at timestamptz default now()
);

-- Create the default settings row
insert into glamsanity_settings (id, company_intro)
values (
    1,
    'Welcome to Glamsanity. We provide cosmetic, skincare, product development, and packaging solutions for businesses looking to build and grow their own beauty brands.'
)
on conflict (id) do nothing;


-- ============================================
-- ENABLE ROW LEVEL SECURITY
-- ============================================

alter table products enable row level security;
alter table containers enable row level security;
alter table bundles enable row level security;
alter table glamsanity_settings enable row level security;


-- ============================================
-- PUBLIC READ ACCESS
-- Clients can see the catalog without logging in.
-- ============================================

create policy "Public can view products"
on products
for select
to anon, authenticated
using (true);

create policy "Public can view containers"
on containers
for select
to anon, authenticated
using (true);

create policy "Public can view bundles"
on bundles
for select
to anon, authenticated
using (true);

create policy "Public can view settings"
on glamsanity_settings
for select
to anon, authenticated
using (true);


-- ============================================
-- ADMIN WRITE ACCESS
-- Only authenticated Supabase users can modify.
-- ============================================

create policy "Authenticated users can add products"
on products
for insert
to authenticated
with check (true);

create policy "Authenticated users can update products"
on products
for update
to authenticated
using (true)
with check (true);

create policy "Authenticated users can delete products"
on products
for delete
to authenticated
using (true);


create policy "Authenticated users can add containers"
on containers
for insert
to authenticated
with check (true);

create policy "Authenticated users can update containers"
on containers
for update
to authenticated
using (true)
with check (true);

create policy "Authenticated users can delete containers"
on containers
for delete
to authenticated
using (true);


create policy "Authenticated users can add bundles"
on bundles
for insert
to authenticated
with check (true);

create policy "Authenticated users can update bundles"
on bundles
for update
to authenticated
using (true)
with check (true);

create policy "Authenticated users can delete bundles"
on bundles
for delete
to authenticated
using (true);


create policy "Authenticated users can update settings"
on glamsanity_settings
for update
to authenticated
using (true)
with check (true);


-- ============================================
-- REALTIME
-- ============================================

alter publication supabase_realtime add table products;
alter publication supabase_realtime add table containers;
alter publication supabase_realtime add table bundles;
alter publication supabase_realtime add table glamsanity_settings;